
using DocumentFunction

@doc """
$(DocumentFunction.documentfunction(shapley;
    location=false,
    maintext="
    The Shapley algorithm (solution concept in cooperative game theory) for computing 
    the Shapley values of a set of agents. The Shapley values are the expected 
    utility of each agent in a set.

    julia> shapley(
        all_ids, ids, (S, data, labels) -> subsec_acc(S, data, labels)
    )
    ",
    argtext=Dict("all_ids"=>"identifiers of all components in the ecosystem",
                 "ids"=>"identifiers of components to be computed shapley values",
                 "subset_acc"=>"subset model with defined output format"),
    keytext=Dict("mc"=>"if true, subsets are generated by monte carlo method (approximation).")))
""" shapley

@doc """
$(DocumentFunction.documentfunction(hiddenagents_shapley;
    location=false,
    maintext="
    Compute Shapley values of hiddent agents components.

    julia> hiddenagents_shapley(
        eco, data, labels, ids, (S, data, labels) -> subsec_acc(S, data, labels)
    )
    ",
    argtext=Dict("eco"=>"neural network ecosystem",
                 "data"=>"input data of the network",
                 "labels"=>"labels corresponding to the data",
                 "subset_acc"=>"subset model with defined output format"),
    keytext=Dict("mc"=>"if true, subsets are generated by monte carlo method (approximation).")))
""" hiddenagents_shapley

@doc """
$(DocumentFunction.documentfunction(inputagents_shapley;
    location=false,
    maintext="
    Compute Shapley values of input agents components.

    julia> hiddenagents_shapley(
        eco, data, labels, ids, (S, data, labels) -> subset_acc(S, data, labels)
    )
    ",
    argtext=Dict("eco"=>"neural network ecosystem",
                 "data"=>"input data of the network",
                 "labels"=>"labels corresponding to the data",
                 "subset_acc"=>"subset model with defined output format"),
    keytext=Dict("mc"=>"if true, subsets are generated by monte carlo method (approximation).")))
""" inputagents_shapley
